# -*- coding: utf-8 -*-
"""Pi-Neural_Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUdiY9RUeFa-iXUjcEMuLwBfbBXFy2Nk
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

st.set_page_config(page_title="Neural Network Estimating Pi", layout="wide")

st.title("Neural Network Learning a Circle to Estimate π")
st.write(
"""
We generate random points in a square [-1,1]×[-1,1].
A neural network learns whether points fall **inside or outside the unit circle**.
Using the ratio of predicted points inside the circle, we estimate **π**.
"""
)

# Sidebar controls
st.sidebar.header("Simulation Controls")

samples = st.sidebar.slider("Training Samples", 2000, 50000, 10000)
epochs = st.sidebar.slider("Training Epochs", 5, 100, 20)
hidden = st.sidebar.slider("Hidden Neurons", 8, 128, 32)
test_points = st.sidebar.slider("Monte Carlo Test Points", 5000, 200000, 50000)

# Generate data
x = np.random.uniform(-1,1,samples)
y = np.random.uniform(-1,1,samples)

X = np.vstack((x,y)).T
labels = (x**2 + y**2 <= 1).astype(int)

X_train,X_test,y_train,y_test = train_test_split(X,labels,test_size=0.2)

# Build model
model = Sequential([
    Dense(hidden,activation='relu',input_shape=(2,)),
    Dense(hidden,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,y_train,
    epochs=epochs,
    verbose=0,
    validation_data=(X_test,y_test)
)

# Monte Carlo prediction
xt = np.random.uniform(-1,1,test_points)
yt = np.random.uniform(-1,1,test_points)

test_data = np.vstack((xt,yt)).T

pred = model.predict(test_data, verbose=0)

inside = pred.flatten() > 0.5

pi_est = 4 * np.sum(inside) / test_points

# Layout
col1,col2 = st.columns(2)

# Monte Carlo visualization
with col1:
    st.subheader("Monte Carlo Sampling")

    fig1,ax1 = plt.subplots(figsize=(5,5))

    ax1.scatter(xt[inside],yt[inside],s=3,label="Inside")
    ax1.scatter(xt[~inside],yt[~inside],s=3,label="Outside")

    ax1.set_title("Random Points Classification")
    ax1.legend()

    st.pyplot(fig1)

# Training curves
with col2:
    st.subheader("Training Performance")

    fig2,ax2 = plt.subplots()

    ax2.plot(history.history['loss'],label="Train Loss")
    ax2.plot(history.history['val_loss'],label="Val Loss")

    ax2.set_title("Training Curve")
    ax2.legend()

    st.pyplot(fig2)

# Decision boundary
st.subheader("Neural Network Learned Circle Boundary")

grid_size = 200

x_vals = np.linspace(-1,1,grid_size)
y_vals = np.linspace(-1,1,grid_size)

xx,yy = np.meshgrid(x_vals,y_vals)

grid = np.c_[xx.ravel(),yy.ravel()]

pred_grid = model.predict(grid, verbose=0)

pred_grid = pred_grid.reshape(grid_size,grid_size)

fig3,ax3 = plt.subplots(figsize=(6,6))

contour = ax3.contourf(xx,yy,pred_grid,levels=50)

ax3.set_title("Neural Network Decision Boundary")

st.pyplot(fig3)

# Pi convergence simulation
st.subheader("π Convergence Visualization")

steps = 1000
counts = []

inside_count = 0

for i in range(1,steps+1):

    px = np.random.uniform(-1,1)
    py = np.random.uniform(-1,1)

    if px**2 + py**2 <= 1:
        inside_count += 1

    counts.append(4 * inside_count / i)

fig4,ax4 = plt.subplots()

ax4.plot(counts)
ax4.axhline(np.pi,linestyle='--')

ax4.set_title("π Estimation Convergence")

st.pyplot(fig4)

# Metrics
st.subheader("Estimated π")

col3,col4,col5 = st.columns(3)

col3.metric("Estimated π", round(float(pi_est),6))
col4.metric("Actual π", round(np.pi,6))
col5.metric("Absolute Error", round(abs(np.pi-pi_est),6))

st.write("""
### Interpretation

The neural network learns the circular boundary separating inside and outside points.
Monte Carlo simulation then estimates π using the ratio of classified points.

This demonstrates how **machine learning + probability + geometry** can recover
fundamental mathematical constants.
""")